configurationset:
  - configuration:
      name: postgresql_config
      uri: postgresql://aws-0-us-east-1.pooler.supabase.com/postgres?user=postgres.lsasjpjghexwczgedzvh&password=Clashofclanz0006%40
